// Ron's 8-bit avatar (approved draft 19, Ron 2026-10-01). Pixel maps copied from
// style-lab/ron8bit/ff.py on the style-agent branch: one character per pixel, "." is empty.
// Colors are tokens: the Japanese palette plus the avatar shades in tokens.css.
export const AVATAR_PALETTE = {
    B: 'var(--kyoto-dusk)',
    G: 'var(--matcha-cream)',
    H: 'var(--charcoal-brew)',
    J: 'var(--charcoal-brew)',
    L: 'var(--avatar-flannel-light)',
    O: 'var(--charcoal-deep)',
    P: 'var(--kyoto-dusk)',
    S: 'var(--vanilla-foam)',
    W: 'var(--white)',
    b: 'var(--avatar-beard)',
    j: 'var(--avatar-far-leg)',
    n: 'var(--terracotta-ink)',
    p: 'var(--avatar-flannel-shade)',
    r: 'var(--roasted-terracotta)',
    s: 'var(--avatar-skin-shade)',
};

export const AVATAR_FRAMES = {
    // Side walk, Step A
    walk0: [
        '................',
        '.......OOO......',
        '.....OOBBHOO....',
        '....OBHHOOBHO...',
        '...OBHOBBHHHHO..',
        '..OBHOBHHHOHHHO.',
        '..OHOBHHHOHHHOO.',
        '...OSSSHOBHHHrBO',
        '..OSOSSSHHsHHOHO',
        '..OSOSSSSHsHHOHO',
        '.OSSSSSSSHHHHOO.',
        '..OsHHSSSSHHO...',
        '..OHnSSSSHHO....',
        '...OHbbbbHO.....',
        '....OOOOOHOO....',
        '.....OWPPPO.....',
        '....OPLPPPpO....',
        '...OPrpppppOO...',
        '..OSSOLPPPpOpO..',
        '..OSSOJJJJJOSSO.',
        '..OOOJJJJJOOOO..',
        '...OJJOOjjO.....',
        '..OGGGOOOGGO....',
        '..OOOOO.OOOO....',
    ],
    // Side walk, Pass A (1px bounce)
    walk1: [
        '.......OOO......',
        '.....OOBBHOO....',
        '....OBHHOOBHO...',
        '...OBHOBBHHHHO..',
        '..OBHOBHHHOHHHO.',
        '..OHOBHHHOHHHOO.',
        '...OSSSHOBHHHrBO',
        '..OSOSSSHHsHHOHO',
        '..OSOSSSSHsHHOHO',
        '.OSSSSSSSHHHHOO.',
        '..OsHHSSSSHHO...',
        '..OHnSSSSHHO....',
        '...OHbbbbHO.....',
        '....OOOOOHOO....',
        '.....OWPPPO.....',
        '....OPLPPPpO....',
        '....OrpppppO....',
        '...sOPLPPSSO....',
        '...sOJJJJSSO....',
        '....OJJJJOOO....',
        '.....OJJJO......',
        '.....OJJjO......',
        '....OGGGOGO.....',
        '....OOOOOOO.....',
    ],
    // Side walk, Step B
    walk2: [
        '................',
        '.......OOO......',
        '.....OOBBHOO....',
        '....OBHHOOBHO...',
        '...OBHOBBHHHHO..',
        '..OBHOBHHHOHHHO.',
        '..OHOBHHHOHHHOO.',
        '...OSSSHOBHHHrBO',
        '..OSOSSSHHsHHOHO',
        '..OSOSSSSHsHHOHO',
        '.OSSSSSSSHHHHOO.',
        '..OsHHSSSSHHO...',
        '..OHnSSSSHHO....',
        '...OHbbbbHO.....',
        '....OOOOOHOO....',
        '.OOOOOWPPPO.....',
        '.OssOPLPPPpO....',
        '.OssOrpppppOPO..',
        '..OOOPLPPPpOSSO.',
        '....OJJJJJJOSSO.',
        '..OOOJJJJJOOOO..',
        '...OjjOOJJO.....',
        '..OGGGO.OJJO....',
        '..OOOOO.OGGO....',
    ],
    // Side walk, Pass B (1px bounce)
    walk3: [
        '.......OOO......',
        '.....OOBBHOO....',
        '....OBHHOOBHO...',
        '...OBHOBBHHHHO..',
        '..OBHOBHHHOHHHO.',
        '..OHOBHHHOHHHOO.',
        '...OSSSHOBHHHrBO',
        '..OSOSSSHHsHHOHO',
        '..OSOSSSSHsHHOHO',
        '.OSSSSSSSHHHHOO.',
        '..OsHHSSSSHHO...',
        '..OHnSSSSHHO....',
        '...OHbbbbHO.....',
        '....OOOOOHOO....',
        '.....OWPPPO.....',
        '....OPLPPPpO....',
        '....OrpppppO....',
        '....OPSSPPpO....',
        '....OJSSJJJOs...',
        '....OJOOJJJO....',
        '.....OJJJO......',
        '....OjjOJJO.....',
        '...OGGOOGGO.....',
        '...OOOOOOOO.....',
    ],
    // Talk pose, hand raised
    talk: [
        '........OO..........',
        '.....OOOBBOOO.......',
        '...OOBBHHHHHBBOO....',
        '..OBHHHOOBBHHHBO....',
        '.OBHHOOBBHHHOBHO....',
        'OBHHOBBHHHOOBHO.....',
        'OHOOBHHHOOBBHHO.....',
        'OHOHHHHHSSSHHHO.....',
        '.OsHHHSSSSOSHsO.....',
        '.OsHSOSSSSOSHsO.....',
        '..OHSSSssSSsHO.OO...',
        '..OHSbHHHHbSHOOSSO..',
        '..OHSSSnnSSSHOOSSO..',
        '...OHbbbbbbHO.OOO...',
        '....OOOOOOOO..OpO...',
        '...OPPOWWOPPO.OpO...',
        '..OLPpPPPPpPpOOpO...',
        '..OprprpprprpppO....',
        '..OLPpPPPPpPpOO.....',
        '..OSOJJJJJJOO.......',
        '..OSOJJJJJJOO.......',
        '....OJJOOJJO........',
        '...OGGOOOOGGO.......',
        '...OOOO..OOOO.......',
    ],
};
